project_name: my_project

directories:
  reads: "my_reads/folder"
  qc_raw: "results/qc/raw"
  trimmed: "results/trimming"
  qc_trimmed: "results/qc/trimmed"
  mapped: "results/salmon/mapped_reads"
  logs: "results/logs"

# Read pattern requires the following wildcards: {sample}=str and {nb}=[1, 2]
read_pattern: "{sample}_R{nb}.fastq.gz"
sample_metadata: "my_metadata.xlsx"
sample_column: "sample_id"

fastp:
  min_phred: 20
  threads: 4
  args:
    - "--trim_poly_g"

salmon:
  index: "path/to/salmon_partial_sa_index"
  args:
    - "-validateMappings"
    - "--gcBias"
    - "--seqBias"
    - "-l A"